"""IBAN envelope encryption (Story 11.10 / TD-049).

Production path: AES-256-GCM with a data encryption key (DEK) generated by AWS
KMS per-call. The DEK ciphertext is prepended to the payload so decryption can
re-derive the DEK via `kms.decrypt` — this keeps the CMK rotation story
zero-downtime (KMS handles historical key versions transparently).

Local-dev path: if `settings.ENV == "local"` and `KMS_IBAN_KEY_ARN` is unset,
fall back to a deterministic Fernet key from `LOCAL_IBAN_FERNET_KEY`. Every
call through this path emits a WARN so the fallback cannot silently escape
to a deployed environment.

Layout of a KMS-produced ciphertext blob:

    [4-byte big-endian len N] [N bytes: KMS-encrypted DEK] [12 bytes: GCM nonce] [GCM ciphertext+tag]

Fernet blobs are distinguished by a single-byte prefix so the two paths can
round-trip independently during local-to-prod migrations.
"""

from __future__ import annotations

import logging
import os
import struct

from cryptography.fernet import Fernet
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from app.core.config import settings

logger = logging.getLogger(__name__)

_KMS_PREFIX = b"\x01"
_FERNET_PREFIX = b"\x02"
_NONCE_LEN = 12


class CryptoConfigError(RuntimeError):
    """Raised when crypto settings are missing for the active environment."""


def _kms_client():
    import boto3  # local import — boto3 is heavy and optional in unit tests

    return boto3.client("kms")


def _use_kms() -> bool:
    return bool(settings.KMS_IBAN_KEY_ARN)


def _require_local_fernet() -> Fernet:
    if settings.ENV != "local":
        raise CryptoConfigError(
            "KMS_IBAN_KEY_ARN unset outside local env — refusing Fernet fallback"
        )
    if not settings.LOCAL_IBAN_FERNET_KEY:
        raise CryptoConfigError(
            "LOCAL_IBAN_FERNET_KEY must be set for local-dev IBAN encryption"
        )
    logger.warning(
        "crypto.fernet_fallback_used "
        "msg='IBAN encryption is using local Fernet fallback — do NOT ship'"
    )
    return Fernet(settings.LOCAL_IBAN_FERNET_KEY.encode())


def encrypt_iban(plaintext: str) -> bytes:
    """Encrypt an IBAN plaintext. Returns opaque bytes; decrypt via decrypt_iban."""
    if not isinstance(plaintext, str) or not plaintext:
        raise ValueError("plaintext must be a non-empty string")

    if _use_kms():
        kms = _kms_client()
        resp = kms.generate_data_key(
            KeyId=settings.KMS_IBAN_KEY_ARN, KeySpec="AES_256"
        )
        dek = resp["Plaintext"]
        dek_ct = resp["CiphertextBlob"]
        nonce = os.urandom(_NONCE_LEN)
        ct = AESGCM(dek).encrypt(nonce, plaintext.encode("utf-8"), None)
        return _KMS_PREFIX + struct.pack(">I", len(dek_ct)) + dek_ct + nonce + ct

    fernet = _require_local_fernet()
    return _FERNET_PREFIX + fernet.encrypt(plaintext.encode("utf-8"))


def decrypt_iban(ciphertext: bytes) -> str:
    """Decrypt an IBAN ciphertext produced by encrypt_iban."""
    if not isinstance(ciphertext, (bytes, bytearray)) or len(ciphertext) < 2:
        raise ValueError("ciphertext is empty or malformed")

    prefix = bytes(ciphertext[:1])
    body = bytes(ciphertext[1:])

    if prefix == _KMS_PREFIX:
        if len(body) < 4:
            raise ValueError("KMS ciphertext truncated")
        (dek_len,) = struct.unpack(">I", body[:4])
        if len(body) < 4 + dek_len + _NONCE_LEN:
            raise ValueError("KMS ciphertext truncated")
        dek_ct = body[4 : 4 + dek_len]
        rest = body[4 + dek_len :]
        nonce = rest[:_NONCE_LEN]
        ct = rest[_NONCE_LEN:]
        kms = _kms_client()
        dek = kms.decrypt(CiphertextBlob=dek_ct)["Plaintext"]
        return AESGCM(dek).decrypt(nonce, ct, None).decode("utf-8")

    if prefix == _FERNET_PREFIX:
        fernet = _require_local_fernet()
        return fernet.decrypt(body).decode("utf-8")

    raise ValueError(f"unknown ciphertext prefix: {prefix!r}")
